### ISSUE TITLE
rev webpack peer dependency?

### ISSUE THREAD

**Issue by cmloegcmluin** [markogresak/ignore-not-found-export-webpack-plugin#8]
npm 7 no longer ignores peer dependency issues when installing. This package hasn't been updated in a while and still calls for webpack 4. We're up to webpack 5 now, but webpack still hasn't fixed the underlying issue. So I now have to remember to use `--legacy-peer-deps`  every time. Perhaps, if there's no difference, you could update the package.json to use a peer dependency of Webpack 5 major version?

**Comment by markogresak** [comment]
@cmloegcmluin thanks for pointing this out, I will check it out. I'm also open to accepting a PR if you're willing to submit one 😄

**Comment by markogresak** [comment]
@cmloegcmluin the problem is fixed with #9, published as patch [v1.0.2](https://github.com/markogresak/ignore-not-found-export-webpack-plugin/releases/tag/v1.0.2).
